### ISSUE TITLE
Publish a Java Package to Github Repository

### ISSUE THREAD

**Issue by mehmet6parmakappcent** [AppcentMobile/helium-java-sdk#4]
Is it possible to achieve this by using the built-in action provided by Github? 
Please have a look at https://github.com/AppcentMobile/helium-java-sdk/actions/new

<img width="796" alt="image" src="https://user-images.githubusercontent.com/110970277/202010386-b36a6e22-e7c9-4eb3-8e6e-41ca086e3e3a.png">

**Comment by mehmet6parmakappcent** [comment]
We've seen Github Maven Repository does not allow anonymous access to packages. So we can't use it. We are considering using Jitpack...

**Comment by erenalpaslan** [comment]
We published our library on jitpack.io
